name: Detekt & Ktlint Check

on:
  pull_request:
    branches:
      - dev
      - staging

jobs:
  set_up:
    uses: scnplt/ram/.github/workflows/set-up.yml@staging
    secrets:
          googleServicesJsonPath: ${{ secrets.GOOGLE_SERVICES_JSON }}

  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2        

      - name: Scan with Ktlint
        run: ./gradlew ktlint

      - name: Scan with Detekt
        run: ./gradlew detekt
