name: Detekt & Ktlint Check

on:
  pull_request:
    branches:
      - dev
      - staging

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Scan with Ktlint
        run: ./gradlew ktlint

      - name: Scan with Detekt
        run: ./gradlew detekt
