name: Detekt & Ktlint Check

on:
  pull_request:
    branches:
      - dev

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Put google-services.json file in all application modules
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: for appFolder in [app]*; do echo $GOOGLE_SERVICES_JSON > $appFolder/google-services.json; done

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Scan with Ktlint
        run: ./gradlew ktlint

      - name: Scan with Detekt
        run: ./gradlew detekt
