name: Detekt & Ktlint Check

on:
  pull_request:
    branches:
      - dev
      - staging

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up dependencies
        uses: ./.github/workflows/set-up.yml
        secrets:
          googleServicesJsonPath: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Scan with Ktlint
        run: ./gradlew ktlint

      - name: Scan with Detekt
        run: ./gradlew detekt
